# Generated by Django 2.2.10 on 2020-02-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0027_auto_20200107_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(default=1, help_text='The submitter will receive an email for all public follow-ups left for this task.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
