# Generated by Django 2.2.10 on 2020-02-07 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0028_ticket_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(blank=True, help_text='The submitter will receive an email for all public follow-ups left for this task.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
